version: "3"

services:
    elasticsearch:
        image: elasticsearch:7.13.2
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"
            - "9300:9300"
        #volumes:
        #    - "elasticsearch-data:?"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.2
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
            - "5601:5601"
        #volumes:
        #    - "kibana-data:?"
        depends_on:
            - elasticsearch

volumes:
    elasticsearch-data:
    kibana-data:

networks:
    default:
        driver: bridge
